config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'offices#index'
  resources :offices, only: [:new, :create, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/office.rb
class Office < ApplicationRecord
  validates :name, :postcode, presence: true
  validates :postcode, format: { without: /\s/ }
  # --- Google Maps api ---
  geocoded_by :postcode
  after_validation :geocode, if: :postcode_changed?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/offices_controller.rb
require 'json'
require 'open-uri'

class OfficesController < ApplicationController

  def index
    if params[:postcode].present?
      @postcode = params[:postcode].gsub(/\s+/, "")
      url = "https://api.postcodes.io/postcodes/#{@postcode}"
      postcode_api = open(url).read
      address = JSON.parse(postcode_api)
      @search_lng = address['result']['longitude']
      @search_lat = address['result']['latitude']
      @search_coords = [@search_lng,@search_lat]
      @all_offices = Office.where.not(latitude: nil, longitude: nil)
      @offices = []
      @all_offices.each do |office|
        office_element = {}
        office_coords = [office.longitude, office.latitude]
        distance = distance(@search_coords, office_coords)
        if distance <= params[:radius].to_f
          office_element[:office] = office
          office_element[:distance] = distance
          @offices << office_element
        end
      end
      @markers = @offices.map do |office|
        {
          lat: office[:office].latitude,
          lng: office[:office].longitude
        }
      end
    else
      @offices = Office.where.not(latitude: nil, longitude: nil)
      @markers = @offices.map do |office|
        {
          lat: office.latitude,
          lng: office.longitude
        }
      end
    end
  end

  def new
    @office = Office.new
  end

  def create
    @office = Office.new(offices_params)
    if @office.save
      redirect_to root_path
    else
      render "new"
    end
  end

  def distance(loc1, loc2)
    rad_per_deg = Math::PI/180  # PI / 180
    rm = 3959                  # Earth radius in miles

    dlat_rad = (loc2[0]-loc1[0]) * rad_per_deg  # Delta, converted to rad
    dlon_rad = (loc2[1]-loc1[1]) * rad_per_deg

    lat1_rad, lon1_rad = loc1.map {|i| i * rad_per_deg }
    lat2_rad, lon2_rad = loc2.map {|i| i * rad_per_deg }

    a = Math.sin(dlat_rad/2)**2 + Math.cos(lat1_rad) * Math.cos(lat2_rad) * Math.sin(dlon_rad/2)**2
    c = 2 * Math::atan2(Math::sqrt(a), Math::sqrt(1-a))

    (rm * c).round(1) # Delta in miles
  end

  def self.sorted_by_percentage_correct
    Office.all.sort_by(&:percentage_correct)
  end

  private

  def offices_params
    params.require(:office).permit(:name, :postcode)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag "map" %>
  </body>
</html>

app/views/offices/index.html.erb
<div class="navbar">
  <div class="left-navbar">
    <a href="/" class="navbar-logo">
      <%= image_tag "noun-map.png", class: "logo" %>
    </a>
    <h1>Find your delivery office</h1>
  </div>
  <div>
    <i class="fa fa-plus" aria-hidden="true"></i>
    <%= link_to "Add office", new_office_path, class: "link" %>
  </div>
</div>
<div class="container">
  <form action="/" method="get" class="form-inline">
    <div class="form-group">
      <input required type="text" name="postcode" class="search-query form-control" placeholder="Postcode" >
    </div>
    <div class="form-group">
      <input required type="text" name="radius" class="search-query form-control" placeholder="Radius [mi]" >
    </div>
    <input type="submit" class="btn btn-danger" id="search-btn" value = "Search">
  </form>

  <div class="list-offices">
    <% if params[:postcode].present? %>
      <% if @offices == [] %>
        <h2>Sorry no results, try increasing the radius!</h2>
        <div>
          <i class="fa fa-undo" aria-hidden="true"></i>
          <%= link_to "Reset", root_path, class: "link" %>
        </div>
      <% else %>
        <h2>Search result for <strong><%= params[:postcode] %></strong> postcode in <strong><%= params[:radius] %></strong> miles radius:</h2>
        <div>
          <i class="fa fa-undo" aria-hidden="true"></i>
          <%= link_to "Reset", root_path, class: "link" %>
        </div>
        <% sorted_offices = @offices.sort_by { |k| k[:distance] } %>
        <% sorted_offices.each do |office| %>
          <div class="office">
            <div>
              <h3><%= office[:office].name.capitalize %></h3>
              <p><%= office[:office].postcode.upcase %></p>
            </div>
            <p><%= office[:distance] %> mi</p>
          </div>
        <% end %>
      <% end %>
    <% else %>
      <h2>All offices:</h2>
      <% @offices.each do |office| %>
        <div class="office">
          <div>
            <h3><%= office.name.capitalize %></h3>
            <p><%= office.postcode.upcase %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div
  id="map"
  style="width: 100%;
  height: 600px;"
  data-markers="<%= @markers.to_json %>"
></div>
</div>

app/views/offices/new.html.erb
<div class="navbar">
  <div class="left-navbar">
    <a href="/" class="navbar-logo">
      <%= image_tag "noun-map.png", class: "logo" %>
    </a>
    <h1>Add a new office</h1>
  </div>
  <div>
    <i class="fa fa-undo" aria-hidden="true"></i>
    <%= link_to "Back to list", root_path, class: "link" %>
  </div>
</div>
<div class="container">
  <%= simple_form_for [@office] do |f| %>
    <div class="form-window">
      <div class="form-group">
        <div class="field">
          <%= f.input :name, class: 'my-label' %>
        </div>
      </div>
      <div class="form-group">
        <div class="field">
          <%= f.input :postcode, label: "Postcode (no spaces)" %>
        </div>
      </div>
      <div class="actions">
        <%= f.submit "Submit your office", class: "btn btn-danger" %>
      </div>
    </div>

  <% end %>
</div>